# Generated by Django 5.1.1 on 2024-09-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_question_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('elementary', 'Elementary'), ('intermediate', 'Intermediate'), ('pre-intermediate', 'Pre-Intermediate'), ('upper-intermediate', 'Upper-Intermediate')], default='beginner', max_length=20),
        ),
    ]
